use_frameworks!

platform :ios, '8.0'

target 'TYJNetworking_Example' do
  pod 'TYJNetworking', :path => '../'

  target 'TYJNetworking_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
